apiVersion: v1
kind: ConfigMap
metadata:
  name: camunda-config
data:
  CAMUNDA_DB_URL: "jdbc:mysql://your-mysql-host:3306/camunda"
  CAMUNDA_DB_USERNAME: "your-db-username"
  CAMUNDA_DB_PASSWORD: "your-db-password"

