# templates/camunda-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camunda-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: {{ .Values.camunda.image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"  # Allocate 512Mi of memory
            requests:
              memory: "256Mi"  # Request 0.2 CPU units
          # Add other Camunda configurations
