# templates/camunda-connectors-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camunda-chart.fullname" . }}-connectors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-connectors
  template:
    metadata:
      labels:
        app: camunda-connectors
    spec:
      containers:
        - name: camunda-connectors
          image: camunda/connectors-bundle:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"  # Allocate 512Mi of memory
            requests:
              memory: "256Mi"  # Request 0.2 CPU units
          # Add other Camunda Connectors configurations
