# templates/camunda-identity-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camunda-chart.fullname" . }}-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-identity
  template:
    metadata:
      labels:
        app: camunda-identity
    spec:
      containers:
        - name: camunda-identity
          image: camunda/identity:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"  # Allocate 512Mi of memory
            requests:
              memory: "256Mi"  # Request 0.2 CPU units
          # Add other Camunda Identity configurations
