# templates/keycloak-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camunda-chart.fullname" . }}-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"  # Allocate 512Mi of memory
            requests:
              memory: "256Mi"  # Request 0.2 CPU units
          # Add other Keycloak configurations
