apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda-chart.fullname" . }}-operate-service
spec:
  selector:
    app: operate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
