# templates/camunda-tasklist-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camunda-chart.fullname" . }}-tasklist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-tasklist
  template:
    metadata:
      labels:
        app: camunda-tasklist
    spec:
      containers:
        - name: camunda-tasklist
          image: camunda/tasklist:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"  # Allocate 0.5 CPU units
            requests:
              cpu: "0.2"  # Request 0.2 CPU units

